=== yddgit/hello-webservice/src/main/resources/dtd/class.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT class (name,grade,students)>
<!ATTLIST class id ID #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT grade (#PCDATA)>
<!ELEMENT students (student*)>
<!ELEMENT student (name, birth)>
<!ATTLIST student id ID #REQUIRED>
<!ELEMENT birth (#PCDATA)>

=== yddgit/hello-webservice/src/main/resources/dtd/class.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE class SYSTEM "class.dtd">
<class id="c1">
	<name>CS1</name>
	<grade>2018</grade>
	<students>
		<student id="s1">
			<name>Jack</name>
			<birth>1980-03-12</birth>
		</student>
		<student id="s2">
			<name>Tom</name>
			<birth>1983-03-12</birth>
		</student>
	</students>
</class>
