=== yddgit/hello-webservice/src/main/resources/dtd/persons.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT persons (person+)>
<!ELEMENT person (gender, name, birth, messages+)>
<!ATTLIST person id ID #REQUIRED>
<!ELEMENT gender (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT birth (#PCDATA)>
<!ELEMENT messages (message+)>
<!ELEMENT message (title, content)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT content (#PCDATA)>

=== yddgit/hello-webservice/src/main/resources/dtd/persons.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE persons SYSTEM "persons.dtd">
<persons>
	<person id="p1">
		<gender>female</gender>
		<name>Ada</name>
		<birth>1989-11-11</birth>
		<messages>
			<message>
				<title>first</title>
				<content>This is a message</content>
			</message>
		</messages>
	</person>
	<person id="p2">
		<gender>male</gender>
		<name>Green</name>
		<birth>1989-11-11</birth>
		<messages>
			<message>
				<title>first</title>
				<content>This is a message</content>
			</message>
		</messages>
	</person>
</persons>
